SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Ignore_Underscore] (
		[id]     [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Ignore_Underscore] SET (LOCK_ESCALATION = TABLE)
GO
